AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: This CloudFormation template

Resources:
  MyStateMachine:
    Type: "AWS::Serverless::StateMachine"
    Properties:
      Name: "SampleWorkFlow"
      Role: "arn:aws:iam::572863632856:role/service-role/StepFunctions-MyStateMachine-y4p0buz3q-role-0a724x17t"
      DefinitionUri: "workflow/hello.yaml"
